name: Self Hosted Test

on:
  push:
    branches: [ main  ]

jobs:
  test:
    runs-on:  self-Hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run:  |
         echo "Self-hosted runner is working!"
         echo "Runner Name: $RUNNER_NAME"
         echo "Job executed successfully"
